employee/employee/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles
from django.contrib.staticfiles.urls import static
from . import settings


urlpatterns = [
    path('', views.login),
    path('register/', views.register),
    # 部门管理
    path('model/list/', views.model_list),
    path('model/add/', views.model_add),
    path('model/delete/', views.model_delete),
    path('model/<int:nid>/use/', views.model_use),
    # 上传文件
    path('upload/', views.upload),
    path('img/upload/', views.img_upload),
    # 用户管理
    path('user/list/', views.user_list),
    path('user/add/', views.user_add),
    path('user/<int:nid>/edit/', views.user_edit),
    path('user/<int:nid>/delete', views.user_delete),
    # 调用模型
    path('use', views.use),
    # 对抗管理
    path('pnum/list/', views.pnum_list),
    path('pnum/add/', views.pnum_add),
    path('pnum/<int:nid>/edit', views.pnum_edit),
    path('pnum/<int:nid>/delete', views.pnum_delete),
    path('model/<int:nid>/use/use/', views.use)


]

employee/app01/models.py
from django.db import models


# Create your models here.
class UserInfo(models.Model):
    """用户表"""
    name = models.CharField(verbose_name="姓名", max_length=32)
    password = models.TextField(verbose_name="密码", max_length=64)
    email = models.EmailField(verbose_name="邮箱", null=True, blank=True)
    # age = models.IntegerField(verbose_name="年龄")
    # gender_choices = (
    #     (1, "男"),
    #     (2, "女"),
    # )
    # gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)
    # 级联删除
    # model = models.ForeignKey(verbose_name="部门", to="app01.AImodel", to_field="id", on_delete=models.CASCADE)
    # 删除置空
    # depart = models.ForeignKey(to="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL)


class AImodel(models.Model):
    """模型表"""
    title = models.CharField(verbose_name='标题', max_length=32)
    def __str__(self):
        return self.title

class Pnum(models.Model):
    """训练历史表"""
    mobile = models.CharField(verbose_name="号码", max_length=11)
    price = models.IntegerField(verbose_name="价格")
    level_choices = (
        (1, "1级"),
        (2, "2级"),
        (3, "3级"),
        (4, "4级"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    status_choices = (
        (1, "已占用"),
        (2, "未占用"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)

employee/app01/views.py
from __future__ import print_function

from django.shortcuts import render, redirect, HttpResponse
from app01 import models
from django import forms
from app01.utils.pagination import Pagination
import torch
from PIL import Image
from get_adv import get_adv
from django.core.validators import RegexValidator


# Create your views here.
def register(request):
    if request.method == "GET":
        form = UserModelForm()
        return render(request, 'register.html', {"form": form})

    form = UserModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect("/model/list/")

    return render(request, 'register.html', {"form": form})


def login(request):
    if request.method == "GET":
        return render(request, 'login.html')

    email = request.POST.get("email")
    password = request.POST.get("password")
    exists = models.UserInfo.objects.filter(email=email).exists()
    if not exists:
        e_error = "该用户不存在"
        return render(request, 'login.html', {"e_error": e_error})
    user = models.UserInfo.objects.filter(email=email).first()
    if password != user.password:
        p_error = "输入密码不正确"
        return render(request, 'login.html', {"p_error": p_error})
    return redirect("/model/list/")


def model_list(request):
    """模型列表"""
    queryset = models.AImodel.objects.all()
    page_object = Pagination(request, queryset, page_size=5)
    content = {
        "queryset": page_object.page_queryset,
        "page_string": page_object.html(),
    }
    return render(request, 'model_list.html', content)


def model_add(request):
    """添加模型"""
    if request.method == "GET":
        return render(request, 'model_add.html')

    my_file = request.FILES.get("pt", None)
    if not my_file:
        error = "上传失败！"
        return render(request, 'model_add.html', {"error": error})
    title = request.POST.get("title")
    destination = open(f"./app01/static/model/{title}.pt", "wb+")
    for chunk in my_file.chunks():
        destination.write(chunk)
    destination.close()
    models.AImodel.objects.create(title=title)
    return redirect("/model/list/")


def model_delete(request):
    """删除模型"""
    nid = request.GET.get('nid')
    models.AImodel.objects.filter(id=nid).delete()
    return redirect("/model/list/")


def model_use(request, nid):
    if request.method == "GET":
        return render(request, 'model_use.html')

    my_file = request.FILES.get("pic", None)
    if not my_file:
        error = "上传失败！"
        return render(request, 'model_use.html', {"error": error})
    title = request.POST.get("title")
    destination = open(f"./app01/static/img/{title}.jpg", "wb+")
    for chunk in my_file.chunks():
        destination.write(chunk)
    destination.close()
    return redirect(request.path + "use")


# 加载文件上传表单
def upload(request):
    return render(request, "upload.html")


# 执行文件上传处理
def img_upload(request):
    my_file = request.FILES.get("pic", None)
    if not my_file:
        return HttpResponse("没有上传的文件信息")
    destination = open("./app01/static/img/a.jpg", "wb+")
    for chunk in my_file.chunks():
        destination.write(chunk)
    destination.close()
    return HttpResponse("上传的文件:")


def use(request, nid):
    print(request.path)
    pretrained_model = "./app01/static/model/FGSM.pt"
    model = torch.load(pretrained_model, map_location="cpu")

    # 设置为验证模式.
    model.eval()
    image_path = "./app01/static/img/a.jpg"
    image = Image.open(image_path).convert("RGB")  # 加载图片并转换为RGB格式
    adv_image, sss = get_adv(model, image)
    adv_image.save("./app01/static/adv_image.jpg")
    request.session['msg']=sss
    #adv_image.show()
    return redirect("/model/" + str(nid) + "/use/")
    
    


def user_list(request):
    queryset = models.UserInfo.objects.all()
    page_object = Pagination(request, queryset, page_size=5)
    content = {
        "queryset": page_object.page_queryset,
        "page_string": page_object.html(),
    }
    return render(request, 'user_list.html', content)


class UserModelForm(forms.ModelForm):
    confirm_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput
    )

    class Meta:
        model = models.UserInfo
        fields = ["name", "email", "password", "confirm_password"]
        widgets = {
            "password": forms.PasswordInput,
            "confirm_password": forms.PasswordInput
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {"class": "form-control", "placeholder": field.label}


def user_add(request):
    if request.method == "GET":
        form = UserModelForm()
        return render(request, 'user_add.html', {"form": form})

    form = UserModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect("/user/list/")

    return render(request, 'user_add.html', {"form": form})


def user_edit(request, nid):
    """编辑用户"""
    row_object = models.UserInfo.objects.filter(id=nid).first()
    if request.method == "GET":
        # 根据ID区数据库获取要编辑的那一行数据
        form = UserModelForm(instance=row_object)
        return render(request, 'usr_edit.html', {'form': form})

    form = UserModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/user/list/')
    return render(request, 'user_add.html', {"form": form})


def user_delete(request, nid):
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect("/user/list/")


def pnum_list(request):
    data_dict = {}
    search_data = request.GET.get('q', "")
    if search_data:
        data_dict["mobile__contains"] = search_data
    queryset = models.Pnum.objects.filter(**data_dict).order_by("-level")
    page_object = Pagination(request, queryset)
    context = {
        "search_data": search_data,
        "queryset": page_object.page_queryset,
        "page_string": page_object.html()
    }
    return render(request, 'pnum_list.html', context)


class PrettyModelForm(forms.ModelForm):
    class Meta:
        model = models.Pnum
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {"class": "form-control", "placeholder": field.label}

    # 验证：方式2
    def clean_mobile(self):
        txt_mobile = self.cleaned_data["mobile"]
        exists = models.Pnum.objects.filter(mobile=txt_mobile).exists()
        if exists:
            raise forms.ValidationError("手机号已存在")
        if len(txt_mobile) != 11:
            raise forms.ValidationError("格式错误")
        return txt_mobile


def pnum_add(request):
    if request.method == "GET":
        form = PrettyModelForm()
        return render(request, 'pnum_add.html', {"form": form})

    form = PrettyModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect("/pnum/list/")

    return render(request, 'pnum_add.html', {"form": form})


class PrettyEditModelForm(forms.ModelForm):
    # mobile = forms.CharField(disabled=True, label="手机号")
    class Meta:
        model = models.Pnum
        fields = ['mobile', 'price', 'level', 'status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {"class": "form-control", "placeholder": field.label}

    def clean_mobile(self):
        txt_mobile = self.cleaned_data["mobile"]
        exists = models.Pnum.objects.exclude(id=self.instance.pk).filter(mobile=txt_mobile).exists()
        if exists:
            raise forms.ValidationError("手机号已存在")
        if len(txt_mobile) != 11:
            raise forms.ValidationError("格式错误")
        return txt_mobile


def pnum_edit(request, nid):
    row_object = models.Pnum.objects.filter(id=nid).first()
    if request.method == "GET":
        form = PrettyEditModelForm(instance=row_object)
        return render(request, 'pnum_edit.html', {"form": form})

    form = PrettyEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/pnum/list/')

    return render(request, 'pnum_edit.html', {"form": form})


def pnum_delete(request, nid):
    models.Pnum.objects.filter(id=nid).delete()
    return redirect("/pnum/list/")

employee/app01/templates/img_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传文件</title>
</head>
<body>
    上传的文件：
</body>
</html>

employee/app01/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>对抗攻击系统</title>
    <link rel="shortcut icon" href="https://img1.imgtp.com/2023/06/09/2b1Syn7P.jpg" type="image/x-icon" />
    <link rel="icon" sizes="any" mask href="https://img1.imgtp.com/2023/06/09/2b1Syn7P.jpg">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/dist/css/bootstrap.css' %}">
    <style>
        .navbar{
            border-radius: 0;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"> 对抗攻击系统 </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/model/list/">模型管理</a></li>
        <li><a href="/user/list/">用户管理</a></li>
        <li><a href="/pnum/list/">对抗管理</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
        <li><a href="https://blog.csdn.net/qq_32275289/article/details/124219347">对抗攻击学习</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">942880223@qq.com <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">个人资料</a></li>
            <li><a href="#">我的信息</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">注销</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div>
    {% block content %}{% endblock %}
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

employee/app01/templates/model_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
             <div class="panel-heading">
                 <h3 class="panel-title"> 上传模型 </h3>
             </div>
             <div class="panel-body">
                 <form class="box" action="" method="POST" enctype="multipart/form-data">
                     {% csrf_token %}
                     <div class="form-group">
                         <label>模型名称</label>
                         <input type="text" class="form-control" placeholder="标题" name="title" />
                     </div>
                     <div class="form-group">
                         <label for="exampleInputFile">模型文件</label>
                         <input type="file" name="pt">
                     </div>
                     <button type="submit" class="btn btn-default">上传</button>
                     <p style="color: red">{{ error }}</p>
                 </form>
             </div>
        </div>
     </div>
{% endblock %}

employee/app01/templates/model_list.html
{% extends 'layout.html' %}

{% block content %}
     <div class="container">
     <div style="margin-bottom: 10px">
         <a class="btn btn-success" href="/model/add/">
             <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
             上传模型
         </a>
     </div>

     <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
          <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
          模型列表
      </div>

      <!-- Table -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>模型名称</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
        {% for obj in queryset %}
          <tr>
            <th>{{ obj.id }}</th>
            <td>{{ obj.title }}</td>
            <td>
                <a class="btn btn-primary btn-xs" href="/model/{{ obj.id }}/use/">测试</a>
                <a class="btn btn-danger btn-xs" href="/model/delete/?nid={{ obj.id }}">删除</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
     <nav aria-label="...">
      <ul class="pagination">
        {{ page_string }}
     </ul>
   </nav>
 </div>
{% endblock %}

employee/app01/templates/model_use.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
         <div class="panel-heading">
             <h3 class="panel-title"> 模型攻击 </h3>
         </div>
         <div class="panel-body">
             <form action="" method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                 <div class="form-group">
                     <label>图片上传</label>
                     <br>
                     <label>图片名字</label>
                     <input type="text" name="title">
                     <input type="file" name="pic" accept="image/*" onchange="displayImage(event);">
                     <img  src="/static/img/a.jpg" width="250" height="250" title="a" alt=" "  />
                     <img id="image" src="" style="height: 50%;width: 500px"/>
                     <script>
                         function displayImage(event) {
                             const reader = new FileReader();
                             reader.onload = function() {
                                 const image = document.getElementById("image");
                                 image.src = reader.result;
                             };
                             reader.readAsDataURL(event.target.files[0]);
                         }
                     </script>
                     <br/><br/>
                 </div>
                 <button type="submit" class="btn btn-default">运行</button>
                 <p style="color: red">{{ error }}</p>
             </form>
         </div>
         <p>类别：{{request.session.msg}}</p>
         <img  src="/static/adv_image.jpg" width="250" height="250" title="a" alt=" "  />
        </div>
    </div>
{% endblock %}。/

employee/app01/templates/pnum_edit.html
{% extends 'layout.html'%}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
         <div class="panel-heading">
             <h3 class="panel-title"> 编辑靓号 </h3>
         </div>
         <div class="panel-body">
             <form method="post" novalidate>
                 {% csrf_token %}
                 {% for field in form %}
                     <div class="form-group">
                     <label>{{ field.label }}</label>
                     {{ field }}
                     <span style="color: red">{{ field.errors.0 }}</span>
                     </div>
                 {% endfor %}
                 <button type="submit" class="btn btn-default">提 交</button>
             </form>
         </div>
     </div>
     </div>
{% endblock %}

employee/app01/templates/pnum_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
     <div style="margin-bottom: 10px" class="clearfix">
         <a class="btn btn-success" href="/pnum/add/">
             <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
             新建靓号
         </a>

         <div style="float: right; width: 300px">
             <form method="get">
                 <div class="input-group">
                     <input type="text" name="q" class="form-control" placeholder="Search for..." value="{{ search_data }}">
                     <span class="input-group-btn">
                     <button class="btn btn-default" type="submit">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                     </button>
                 </span>
             </div>
             </form>
     </div>

     <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
          <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
          靓号列表
      </div>

      <!-- Table -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>号码</th>
            <th>价格</th>
            <th>级别</th>
            <th>状态</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
        {% for obj in queryset %}
          <tr>
            <th>{{ obj.id }}</th>
            <td>{{ obj.mobile }}</td>
            <td>{{ obj.price }}</td>
            <td>{{ obj.get_level_display }}</td>
            <td>{{ obj.get_status_display }}</td>
            <td>
                <a class="btn btn-primary btn-xs" href="/pnum/{{ obj.id }}/edit">编辑</a>
                <a class="btn btn-danger btn-xs" href="/pnum/{{ obj.id }}/delete">删除</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

     <nav aria-label="...">
      <ul class="pagination">
        {{ page_string }}
     </ul>
   </nav>
 </div>
{% endblock %}

employee/app01/templates/pt_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

employee/app01/templates/register.html
<!DOCTYPE html>
<html>
<!--STATUS OK-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>
        注册帐号
    </title>

    <link rel="shortcut icon" href="https://img1.imgtp.com/2023/06/09/2b1Syn7P.jpg" type="image/x-icon" />
    <link rel="icon" sizes="any" mask href="https://img1.imgtp.com/2023/06/09/2b1Syn7P.jpg">
    <script type="text/javascript" nonce="s1Pt3G0MsbRem2LQ">
        window.wpo = { start: new Date * 1, pid: 109, page: 'passport' };
        const _hmt = _hmt || [];
    </script>
    <link href="https://ppui-static-pc.cdn.bcebos.com/static/passpc-base/css/base.css?cdnversion=1686293127"
        type="text/css" rel="stylesheet" />
    <link href="https://ppui-static-pc.cdn.bcebos.com/static/passpc-base/css/ui/ui.css?cdnversion=1686293127"
        type="text/css" rel="stylesheet" />
    <link href="https://ppui-static-pc.cdn.bcebos.com/static/passpc-account/css/boot_reg_a65c431.css" type="text/css"
        rel="stylesheet" />
    <link href="https://ppui-static-pc.cdn.bcebos.com/static/passpc-account/css/show/reg/reg_new_ccb052b.css"
        type="text/css" rel="stylesheet">
</head>

<body>
    <div id="wrapper" class="reg-content">
        <div id="head">
        </div>
        <div id="nav">
        </div>
        <div id="content">
            <div class="mod-new-reg-bg">
                <img src="/static/passpc-account/img/reg_bg_min.jpg">
            </div>
            <div class="mod-new-reg-wrapper">
                <div class="mod-new-reg-text">
                    <h3>用对抗</h3>
                    <p>
                        让你的模型更安全 </p>
                </div>
            </div>
            <div class="mod-reg clearfix mod-reg- mod-new-reg-content ">
                <div class="new-reg-guide-login">
                    <h3>
                        欢迎使用 </h3>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">注册</h3>
                        </div>
                        <div class="panel-body">
                            <form method="post" novalidate class="pass-input-container" >
                                <style>
                                    .form-control {
                                        padding: 11px 10px;
                                        max-height: 40px;
                                        background: #fff;
                                        border: 1px solid #E0E0E0;
                                        border-radius: 4px;
                                        font-size: 14px;
                                        width: 321px;
                                        color: #000;
                                    }

                                    .text {
                                        font-size: 14px;
                                        color: #333;
                                        letter-spacing: 0;
                                        text-align: right;
                                        width: 82px;
                                        height: 40px;
                                        line-height: 40px;
                                        margin-right: 15px;
                                        font-weight: 200;
                                        display: block;
                                        float: left;
                                    }

                                    .btn {
                                        display: block;
                                        float: left;
                                        width: 120px;
                                        height: 30px;
                                        font-size: 16px;
                                        font-weight: 700;
                                        cursor: pointer;
                                        color: #0e0f0f;
                                        border-radius: 3px;
                                        border: 0;
                                        -moz-border-radius: 3px;
                                        -webkit-border-radius: 3px;
                                        transition: .3s;
                                        -moz-transition: .3s;
                                        -o-transition: .3s;
                                        -webkit-transition: .3s;
                                        background: #BDCEFC none;
                                        border-radius: 25px;

                                    }
                                </style>
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">{{ field.label }}</label>
                                        <div class="col-sm-10">
                                            {{ field }}
                                        </div>
                                        <span style="color: red">{{ field.errors.0 }}</span>
                                    </div>
                                {% endfor %}
{#                                <div class="form-group">#}
{#                                    <label for="exampleInputEmail1" class="col-sm-2 control-label">用户名</label>#}
{#                                    <div class="col-sm-10">#}
{#                                        <input type="text" class="form-control" name="name" placeholder="名称">#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="form-group">#}
{#                                    <label for="exampleInputEmail1" class="col-sm-2 control-label">邮   箱</label>#}
{#                                    <div class="col-sm-10">#}
{#                                        <input type="email" class="form-control" name="email" placeholder="邮箱">#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="form-group">#}
{#                                    <label for="exampleInputPassword1" class="col-sm-2 control-label">密   码</label>#}
{#                                    <div class="col-sm-10">#}
{#                                        <input type="password" class="form-control" name="password" placeholder="密码">#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="form-group">#}
{#                                    <label for="exampleInputPassword1" class="col-sm-2 control-label">确认密码</label>#}
{#                                    <div class="col-sm-10">#}
{#                                        <input type="password" class="form-control" name="password2" placeholder="请再次输入密码">#}
{#                                    </div>#}
{#                                    <span style="color: red">{{ error }}</span>#}
{#                                </div>#}
                                <br>
                                <button type="submit" class="btn btn-default">登录</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div id="foot">
            </div>
        </div>

</body>

</html>

employee/app01/templates/upload.html
<!DOCYPYE HTML>
<HTML lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width,initial-scale=1.0">
     <title>Document</title>
</head>
<body>
    <h2>文件上传实例</h2>
    <form  action="/img/upload/" method="post" enctype="multipart/form-data">
          {% csrf_token %}
         <input type="text" placeholder="" name="title"/><br/><br/>
         <input type="file" name="pic"/><br/><br/>
         <input type="submit" value="上传"/>
    </form>
</body>
<html>

employee/app01/templates/use.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

employee/app01/templates/user_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
         <div class="panel-heading">
             <h3 class="panel-title"> 新建用户 </h3>
         </div>
         <div class="panel-body">
             <form method="post" novalidate>
                 {% csrf_token %}
                 {% for field in form %}
                     <div class="form-group">
                     <label>{{ field.label }}</label>
                     {{ field }}
                     <span style="color: red">{{ field.errors.0 }}</span>
                     </div>
                 {% endfor %}
                 <button type="submit" class="btn btn-default">提 交</button>
             </form>
         </div>
     </div>
     </div>
{% endblock %}

employee/app01/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
    <div style="margin-bottom: 10px">
         <a class="btn btn-success" href="/user/add/">
             <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
             新建用户
         </a>
     </div>

    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
          <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
          用户列表
      </div>

      <!-- Table -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>姓名</th>
            <th>邮箱</th>
            <th>密码</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
        {% for obj in queryset %}
          <tr>
            <th>{{ obj.id }}</th>
            <td>{{ obj.name }}</td>
            <td>{{ obj.email}}</td>
            <td>********</td>
            <td>
                <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit">编辑</a>
                <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete">删除</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <nav aria-label="...">
      <ul class="pagination">
        {{ page_string }}
     </ul>
   </nav>
 </div>
{% endblock %}